### ISSUE TITLE
strategy maximizing RoI from CT

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hoprsim#9]
Is there an optimal strategy to manage payment channels and stake to optimize RoI?

TODO:
- [ ] manually try in tiny network what strategy could be, using `hoprsim.py`
- [ ] define the strategy and implement in function
- [ ] check what happens if all nodes follow that strategy, e.g. centralization / star topology or other adverse results on network level

**Comment by Eleonora0119** [comment]
The first two are done, but can't check them out

**Comment by Eleonora0119** [comment]
Waiting for feedback on the actual status, code is available: https://github.com/hoprnet/hopr-devrel/blob/main/analytics/ct_strategy_game/ct_strategy_game_v1.ipynb

**Comment by nionis** [comment]
@Eleonora0119 could you update the tasks on what was done?

**Comment by SCBuergel** [comment]
Nora provided a python notebook which
- analyzed dominance of 3 different strategy based on a fitting algorithm
- analyzed the outcome on the network when iteratively applying the dominant strategy to all nodes, it also
  - analyzes the dynamics of that (how long does it take to reach stability, e.g. 2 iterations)
  - what is the centralization of this network
  
An internal report can be found [here](https://docs.google.com/document/d/1bd9ygsYbvCDpfeqOJKkdATYsDPcks3BreLuGGijzvxQ/edit)

**Comment by Eleonora0119** [comment]
Code:
https://github.com/hoprnet/hopr-devrel/tree/main/analytics/ct_strategy_game
Conclusions
https://docs.google.com/document/d/1bd9ygsYbvCDpfeqOJKkdATYsDPcks3BreLuGGijzvxQ/edit
